In [27]:
import numpy as np
import pandas as pd
from DS_Planck_Unet import train_pix_act, val_pix, test_pix, train_pix

In [2]:
df = pd.read_csv('/home/rt2122/Data/detected_cats/full_pz_act_rot_drop0.1_ep9_thr0.1_step8.csv')

In [3]:
df

,RA,DEC,area,min_rad,max_rad,mean_rad,min_pred,max_pred,tRA,tDEC,status,catalog
0,284.569689,24.998012,3.0,0.468950,2.126332,1.197122,0.106447,0.110319,NaN,NaN,fp,NaN
1,278.743982,38.290619,5.0,0.633251,2.638718,1.494957,0.101122,0.120779,NaN,NaN,fp,NaN
2,283.885203,24.263104,6.0,0.482908,2.523304,1.564517,0.110225,0.145304,NaN,NaN,fp,NaN
3,278.388155,36.296444,2.0,0.460727,1.835582,1.102004,0.102068,0.119469,NaN,NaN,fp,NaN
4,282.018745,27.762795,7.0,0.996215,2.830549,1.629188,0.100331,0.113046,NaN,NaN,fp,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...
18797,234.825380,-80.565740,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,fn,planck_no_z
18798,255.913123,-81.428948,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,fn,planck_no_z
18799,313.550387,-76.786726,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,fn,planck_no_z
18800,229.612406,-81.503022,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,fn,planck_z
18801,281.798395,-63.289830,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,fn,planck_z

In [4]:
np.count_nonzero(np.isnan(df['max_pred']))

4578

In [5]:
df = df[df['status'] != 'fn']
np.count_nonzero(np.isnan(df['max_pred']))

0

In [22]:
df.to_csv('/home/rt2122/Data/detected_cats/full_pz_act_rot_drop0.1_ep9_thr0.1_step8_no_fn.csv', index=False)

In [17]:
def mark_cat(cat, d):
    import numpy as np
    import pandas as pd
    from DS_healpix_fragmentation import radec2pix
    
    pix2 = radec2pix(cat['RA'], cat['DEC'], 2)
    cat['pix2'] = ''
    for name in d:
        cat['pix2'].loc[np.in1d(pix2, d[name])] = name
    return cat

In [5]:
df = pd.read_csv('/home/rt2122/Data/detected_cats/full_pz_act_rot_drop0.1_ep9_thr0.1_step8_no_fn.csv')

In [18]:
df = mark_cat(df, {'train_pix_act' : train_pix_act, 'val_pix' : val_pix, 'test_pix' : test_pix})

/home/rt2122/anaconda3/lib/python3.8/site-packages/pandas/core/indexing.py:671: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self._setitem_with_indexer(indexer, value)

In [19]:
df

,RA,DEC,area,min_rad,max_rad,mean_rad,min_pred,max_pred,tRA,tDEC,status,catalog,pix2
0,284.569689,24.998012,3.0,0.468950,2.126332,1.197122,0.106447,0.110319,NaN,NaN,fp,NaN,
1,278.743982,38.290619,5.0,0.633251,2.638718,1.494957,0.101122,0.120779,NaN,NaN,fp,NaN,
2,283.885203,24.263104,6.0,0.482908,2.523304,1.564517,0.110225,0.145304,NaN,NaN,fp,NaN,
3,278.388155,36.296444,2.0,0.460727,1.835582,1.102004,0.102068,0.119469,NaN,NaN,fp,NaN,
4,282.018745,27.762795,7.0,0.996215,2.830549,1.629188,0.100331,0.113046,NaN,NaN,fp,NaN,
...,...,...,...,...,...,...,...,...,...,...,...,...,...
14219,234.833852,-83.666376,3.0,0.458561,2.176377,1.217943,0.100661,0.121112,234.891000,-83.592000,tp,mcxcwp,
14220,232.903029,-65.553512,8.0,0.261180,2.481906,1.705625,0.100690,0.143738,232.924314,-65.521357,tp,planck_no_z,
14221,216.232372,-77.471267,26.0,2.034317,4.374887,3.017533,0.102253,0.576949,216.094587,-77.426749,tp,planck_no_z,
14222,208.658916,-73.109369,10.0,1.101799,3.209450,1.913898,0.117922,0.207947,208.660711,-73.043977,tp,planck_z,
14223,139.785006,-81.075169,46.0,2.096947,5.492463,3.909223,0.105688,0.849405,139.760486,-81.056965,tp,planck_z,

In [20]:
set(df['pix2'])

{'', 'test_pix', 'train_pix_act', 'val_pix'}

In [21]:
df[df['pix2'] == 'test_pix']

,RA,DEC,area,min_rad,max_rad,mean_rad,min_pred,max_pred,tRA,tDEC,status,catalog,pix2
1996,315.818890,82.098373,25.0,0.947670,5.308295,3.095890,0.102180,0.261519,NaN,NaN,fp,NaN,test_pix
1997,317.910196,78.764451,2.0,0.458403,1.768316,1.077337,0.113703,0.134338,NaN,NaN,fp,NaN,test_pix
1998,317.845018,78.907081,5.0,0.111375,3.268127,1.733594,0.102168,0.148746,NaN,NaN,fp,NaN,test_pix
1999,313.574016,82.480774,54.0,2.134985,10.444648,5.052675,0.103341,0.908728,NaN,NaN,fp,NaN,test_pix
2000,163.083936,78.549791,1.0,0.000000,1.414214,0.853553,0.102775,0.102775,NaN,NaN,fp,NaN,test_pix
...,...,...,...,...,...,...,...,...,...,...,...,...,...
2144,223.287020,58.090154,32.0,1.841631,4.166431,3.257196,0.110805,0.894600,223.248775,58.036577,tp,planck_z,test_pix
2145,238.174411,62.082090,6.0,0.217671,2.350315,1.529793,0.101765,0.148675,238.134593,62.054477,tp,planck_z,test_pix
2146,218.924036,55.181897,21.0,0.992577,4.227321,2.709685,0.103763,0.448178,218.838751,55.141350,tp,planck_z,test_pix
2147,227.065537,57.956302,38.0,1.717612,5.723738,3.661999,0.103397,0.686409,227.061350,57.891783,tp,planck_z,test_pix
2148,216.630597,51.273270,2.0,0.487440,1.792339,1.085993,0.111644,0.117397,216.634711,51.252090,tp,planck_no_z,test_pix

In [23]:
df = pd.read_csv('/home/rt2122/Data/detected_cats/full_pz14_thr0.1_step8.csv')

In [25]:
df = df[df['status'] != 'fn']
df.index = np.arange(len(df))
df

,RA,DEC,area,min_rad,max_rad,mean_rad,min_pred,max_pred,tRA,tDEC,status,catalog
0,278.729165,38.316797,19.0,1.432709,4.004335,2.520510,0.108317,0.413399,NaN,NaN,fp,NaN
1,280.203190,35.200291,4.0,0.669169,2.150018,1.330912,0.102844,0.136218,NaN,NaN,fp,NaN
2,282.443666,29.119489,7.0,0.674509,2.539858,1.685457,0.105349,0.206998,NaN,NaN,fp,NaN
3,283.885203,24.263104,15.0,0.910729,3.338126,2.266271,0.126845,0.390404,NaN,NaN,fp,NaN
4,284.942656,19.292361,9.0,0.726939,2.579206,1.818906,0.111344,0.204963,NaN,NaN,fp,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...
17963,205.513747,-81.296854,3.0,0.058481,2.288524,1.279604,0.101794,0.123250,205.579416,-81.278848,tp,planck_no_z
17964,216.108966,-77.460988,22.0,1.433088,3.635538,2.728943,0.172408,0.961364,216.094586,-77.426749,tp,planck_no_z
17965,147.253311,-83.465108,2.0,0.455064,1.840333,1.103797,0.100661,0.120541,147.164000,-83.465000,tp,mcxcwp
17966,208.626743,-73.072567,31.0,2.253890,4.401233,3.224529,0.133330,0.994264,208.660711,-73.043977,tp,planck_z
17967,139.798996,-81.046621,28.0,1.987244,4.353037,3.114186,0.125027,0.971545,139.760486,-81.056965,tp,planck_z

In [29]:
df.to_csv('/home/rt2122/Data/detected_cats/full_pz14_thr0.1_step8_no_fn.csv', index=False)

In [28]:
df = mark_cat(df, {'train_pix' : train_pix, 'val_pix' : val_pix, 'test_pix' : test_pix})
df

<ipython-input-17-ce62105dade1>:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  cat['pix2'] = ''
/home/rt2122/anaconda3/lib/python3.8/site-packages/pandas/core/indexing.py:671: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self._setitem_with_indexer(indexer, value)
<ipython-input-17-ce62105dade1>:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  cat['pix2'].loc[np.in1d(pix2, d[name])] = name

,RA,DEC,area,min_rad,max_rad,mean_rad,min_pred,max_pred,tRA,tDEC,status,catalog,pix2
0,278.729165,38.316797,19.0,1.432709,4.004335,2.520510,0.108317,0.413399,NaN,NaN,fp,NaN,train_pix
1,280.203190,35.200291,4.0,0.669169,2.150018,1.330912,0.102844,0.136218,NaN,NaN,fp,NaN,train_pix
2,282.443666,29.119489,7.0,0.674509,2.539858,1.685457,0.105349,0.206998,NaN,NaN,fp,NaN,train_pix
3,283.885203,24.263104,15.0,0.910729,3.338126,2.266271,0.126845,0.390404,NaN,NaN,fp,NaN,train_pix
4,284.942656,19.292361,9.0,0.726939,2.579206,1.818906,0.111344,0.204963,NaN,NaN,fp,NaN,train_pix
...,...,...,...,...,...,...,...,...,...,...,...,...,...
17963,205.513747,-81.296854,3.0,0.058481,2.288524,1.279604,0.101794,0.123250,205.579416,-81.278848,tp,planck_no_z,train_pix
17964,216.108966,-77.460988,22.0,1.433088,3.635538,2.728943,0.172408,0.961364,216.094586,-77.426749,tp,planck_no_z,train_pix
17965,147.253311,-83.465108,2.0,0.455064,1.840333,1.103797,0.100661,0.120541,147.164000,-83.465000,tp,mcxcwp,train_pix
17966,208.626743,-73.072567,31.0,2.253890,4.401233,3.224529,0.133330,0.994264,208.660711,-73.043977,tp,planck_z,train_pix
17967,139.798996,-81.046621,28.0,1.987244,4.353037,3.114186,0.125027,0.971545,139.760486,-81.056965,tp,planck_z,train_pix