Пояснение по gen_table: параметр dict_cut выбирает, как обрезать каталоги.

Например при dict_cut = {'z' : [0.1, 0.3]} в каталогах останутся только объекты с 0.1 =< z < 0.3. 

Для b используется модуль: dict_cut = {'b' : [20, np.inf]} оставит в каталогах объекты для которых |b| >= 20

In [1]:
import numpy as np
import pandas as pd
import os
from matplotlib import pyplot as plt
from astropy.io import fits
from astropy.table import Table
from astropy.coordinates import SkyCoord
from astropy import units as u
from DS_healpix_fragmentation import radec2pix
from DS_Planck_Unet import val_pix

In [2]:
def get_name(file):
    if 'pz_act' in file:
        return file[5:13]
    return file[5:9]

In [3]:
def calc_error(det_cat, true_cat, shift=15/60, match_dist=5/60, n_try=20, seed=0):
    import numpy as np
    from astropy.coordinates import SkyCoord
    from astropy import units as u
    
    error = []
    np.random.seed(seed)
    for i in range(n_try):
        det_sc = SkyCoord(ra=np.array(det_cat['RA']) * u.degree, 
                          dec=np.array(det_cat['DEC']) * u.degree, frame='icrs')
        angles = np.random.randint(0, 360, len(det_cat))
        det_sc = det_sc.directional_offset_by(angles*u.degree, shift)

        true_sc = SkyCoord(ra=np.array(true_cat['RA']) * u.degree, 
                           dec=np.array(true_cat['DEC']) * u.degree, frame='icrs')
        _, d2d, _ = det_sc.match_to_catalog_sky(true_sc)
        c_error = np.count_nonzero(d2d.degree < match_dist)
        error.append(c_error)
    error = np.array(error)
    return error.mean(), error.std() / np.sqrt(n_try - 1)

In [4]:
def cut_cat(df, dict_cut = {'z' : [-np.inf, np.inf], 'M500' : [-np.inf, np.inf], 'b' :[-np.inf, np.inf]}, 
           big_pix=None):
 
    sc = SkyCoord(ra=np.array(df['RA'])*u.degree, 
                  dec=np.array(df['DEC'])*u.degree, frame='icrs')
    df['b'] = sc.galactic.b.degree
    for prm in dict_cut:
        if prm == 'b':
            df = df[np.abs(df[prm]) >= dict_cut[prm][0]]
            df = df[np.abs(df[prm]) < dict_cut[prm][1]]
            
        df = df[df[prm] >= dict_cut[prm][0]]
        df = df[df[prm] < dict_cut[prm][1]]
    df.index = np.arange(len(df))
    
    if not (big_pix is None):
        pix2 = radec2pix(df['RA'], df['DEC'], 2)
        df = df[np.in1d(pix2, big_pix)]
        df.index = np.arange(len(df))
    
    return df

In [5]:
def gen_tables(det_cats_files, true_cats_files, dict_cut = {'z' : [-np.inf, np.inf], 'M500' : [-np.inf, np.inf], 
                        'b' :[-np.inf, np.inf]}, big_pix = None, match_dist=5/60):
    
    true_cats = {os.path.splitext(os.path.basename(file))[0] : pd.read_csv(file) for file in true_cats_files}
    det_cats = {get_name(os.path.splitext(os.path.basename(file))[0]) : 
                pd.read_csv(file) for file in det_cats_files}
    
    comp_df = []
    recall_df = []
    
    for name in det_cats:
        df = det_cats[name]
        df = df[df['status'] != 'fn']
        df.index = np.arange(len(df))
        if 'b' in dict_cut:
            det_cats[name] = cut_cat(df, {'b' : dict_cut['b']}, big_pix)
        else:
            det_cats[name] = cut_cat(df, {}, big_pix)
    for name in true_cats:
        true_cats[name] = cut_cat(true_cats[name], dict_cut, big_pix)
    
    for det_name in det_cats:
        det = det_cats[det_name]
        line = {}
        line_r = {}

        det_sc = SkyCoord(ra=np.array(det['RA'])*u.degree, 
                      dec=np.array(det['DEC'])*u.degree, frame='icrs') 

        for tr_name in true_cats: 
            tr = true_cats[tr_name]
            tr_sc = SkyCoord(ra=np.array(tr['RA'])*u.degree, 
                          dec=np.array(tr['DEC'])*u.degree, frame='icrs')
            
            idx, d2d, _ = tr_sc.match_to_catalog_sky(det_sc)
            matched = d2d.degree <= match_dist
            
            line[tr_name] = np.count_nonzero(matched)
            line[tr_name+'_err'], line[tr_name+'_std'] = calc_error(det, tr)

            line_r[tr_name] = line[tr_name] / len(tr)
            
        line['all'] = len(det)
        line['fp'] = np.count_nonzero(det['status'] == 'fp')
        line_r['fp'] = line['fp']
        line_r['all'] = line['all']
        comp_df.append(pd.DataFrame(line, index=[det_name]))
        recall_df.append(pd.DataFrame(line_r, index=[det_name]))
        line = {}
    
    for tr_name in true_cats: 
        line[tr_name] = len(true_cats[tr_name])
        line[tr_name+'_err'] = 0
    line['fp'] = 0
    line['all'] = 0
    comp_df.append(pd.DataFrame(line, index=['all']))
    
    comp_df = pd.concat(comp_df)
    recall_df = pd.concat(recall_df)
    
    return comp_df, recall_df

In [8]:
tr_dir = '/home/rt2122/Data/original_catalogs/csv/'
true_cats_files = [os.path.join(tr_dir, name) for name in next(os.walk(tr_dir))[-1]]
det_dir = '/home/rt2122/Data/detected_cats/'
det_cats_files = [os.path.join(det_dir, name) for name in sorted(next(os.walk(det_dir))[-1]) if 'full' in name]
#det_cats_files = ['/home/rt2122/Data/detected_cats/full_pz14_thr0.1_step8.csv', 
#                 '/home/rt2122/Data/detected_cats/full_pz_act10_thr0.1_step8.csv']

In [8]:
comp, recall = gen_tables(det_cats_files, true_cats_files, dict_cut={'b' : [20, np.inf]})
comp

<ipython-input-4-62a47b50d5ee>:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['b'] = sc.galactic.b.degree

,PSZ2,PSZ2_err,PSZ2_std,MCXC,MCXC_err,MCXC_std,RM,RM_err,RM_std,ACT,ACT_err,ACT_std,all,fp
pz14,591,6.10,0.593385,332,9.50,0.748683,939,202.35,3.354710,246,19.30,0.987021,7112,6266
pz20,608,7.10,0.496832,342,9.60,0.563822,977,206.95,3.350943,251,18.75,0.790985,7329,6458
pz25,601,6.85,0.488149,345,9.00,0.676679,1052,227.00,3.728976,246,18.90,0.981138,7946,7082
pz40,597,6.70,0.607410,344,9.70,0.781699,967,215.60,2.574572,256,19.80,1.340856,7678,6810
pz_act06,505,2.35,0.424729,261,4.50,0.483953,563,85.45,1.709840,192,9.70,0.873890,2923,2263
pz_act10,538,3.75,0.415964,308,7.05,0.617614,781,143.65,2.900340,302,13.50,0.738063,4772,3952
pz_act14,548,5.10,0.475173,314,8.80,0.713037,922,186.25,2.853322,476,18.80,0.869362,5963,4958
pz_act20,512,4.20,0.456532,281,6.20,0.432861,882,134.90,2.871732,690,15.35,1.119857,4385,3206
pz_act25,514,4.50,0.366348,277,5.80,0.526158,918,147.45,2.329982,780,14.85,1.044472,4988,3718
all,644,0.00,NaN,917,0.00,NaN,17816,0.00,NaN,1469,0.00,NaN,0,0

In [9]:
recall

              PSZ2      MCXC        RM       ACT    fp   all
pz14      0.917702  0.362050  0.052705  0.167461  6266  7112
pz20      0.944099  0.372955  0.054838  0.170865  6458  7329
pz25      0.933230  0.376227  0.059048  0.167461  7082  7946
pz40      0.927019  0.375136  0.054277  0.174268  6810  7678
pz_act06  0.784161  0.284624  0.031601  0.130701  2263  2923
pz_act10  0.835404  0.335878  0.043837  0.205582  3952  4772
pz_act14  0.850932  0.342421  0.051751  0.324030  4958  5963
pz_act20  0.795031  0.306434  0.049506  0.469707  3206  4385
pz_act25  0.798137  0.302072  0.051527  0.530973  3718  4988

In [10]:
true_cats_files = [file for file in true_cats_files if not ('RM' in file)]

In [11]:
comp, recall = gen_tables(det_cats_files, true_cats_files, dict_cut={'M500' : [3, np.inf], 'b' : [20, np.inf]})
comp

<ipython-input-4-62a47b50d5ee>:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['b'] = sc.galactic.b.degree

,PSZ2,PSZ2_err,PSZ2_std,MCXC,MCXC_err,MCXC_std,ACT,ACT_err,ACT_std,all,fp
pz14,390,4.00,0.528155,158,1.70,0.272416,110,3.80,0.367065,7112,6266
pz20,395,4.50,0.407173,156,1.70,0.325253,109,3.00,0.390681,7329,6458
pz25,395,4.75,0.512348,156,2.00,0.340279,107,2.95,0.343932,7946,7082
pz40,393,4.50,0.564288,154,2.15,0.318508,110,4.20,0.521132,7678,6810
pz_act06,349,1.75,0.298020,143,0.95,0.294467,88,1.60,0.365629,2923,2263
pz_act10,361,2.60,0.365629,151,1.60,0.293795,112,2.20,0.381134,4772,3952
pz_act14,368,3.65,0.418487,153,2.30,0.370632,134,3.00,0.316228,5963,4958
pz_act20,351,2.80,0.337171,147,1.50,0.211511,166,2.70,0.291096,4385,3206
pz_act25,352,2.90,0.270477,144,1.40,0.255467,176,2.50,0.336389,4988,3718
all,399,0.00,NaN,199,0.00,NaN,240,0.00,NaN,0,0

In [12]:
recall

              PSZ2      MCXC       ACT    fp   all
pz14      0.977444  0.793970  0.458333  6266  7112
pz20      0.989975  0.783920  0.454167  6458  7329
pz25      0.989975  0.783920  0.445833  7082  7946
pz40      0.984962  0.773869  0.458333  6810  7678
pz_act06  0.874687  0.718593  0.366667  2263  2923
pz_act10  0.904762  0.758794  0.466667  3952  4772
pz_act14  0.922306  0.768844  0.558333  4958  5963
pz_act20  0.879699  0.738693  0.691667  3206  4385
pz_act25  0.882206  0.723618  0.733333  3718  4988

In [13]:
comp, recall = gen_tables(det_cats_files, true_cats_files, dict_cut={'M500' : [4, np.inf], 'b' : [20, np.inf]})
comp

<ipython-input-4-62a47b50d5ee>:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['b'] = sc.galactic.b.degree

,PSZ2,PSZ2_err,PSZ2_std,MCXC,MCXC_err,MCXC_std,ACT,ACT_err,ACT_std,all,fp
pz14,310,3.10,0.475173,95,1.25,0.216126,56,1.20,0.200000,7112,6266
pz20,314,3.60,0.327671,95,1.00,0.240613,57,1.00,0.217643,7329,6458
pz25,313,4.05,0.510289,94,1.30,0.291096,61,1.15,0.220943,7946,7082
pz40,311,3.85,0.488149,93,1.00,0.240613,61,1.25,0.260314,7678,6810
pz_act06,284,1.40,0.275299,94,0.75,0.227977,48,0.80,0.212751,2923,2263
pz_act10,288,2.20,0.304354,95,0.75,0.203586,58,0.75,0.203586,4772,3952
pz_act14,293,2.95,0.373286,96,1.15,0.264326,64,0.80,0.295581,5963,4958
pz_act20,282,2.25,0.298020,95,0.75,0.160181,68,0.70,0.146898,4385,3206
pz_act25,285,2.00,0.205196,94,0.60,0.222427,70,0.90,0.190567,4988,3718
all,316,0.00,NaN,112,0.00,NaN,85,0.00,NaN,0,0

In [14]:
recall

              PSZ2      MCXC       ACT    fp   all
pz14      0.981013  0.848214  0.658824  6266  7112
pz20      0.993671  0.848214  0.670588  6458  7329
pz25      0.990506  0.839286  0.717647  7082  7946
pz40      0.984177  0.830357  0.717647  6810  7678
pz_act06  0.898734  0.839286  0.564706  2263  2923
pz_act10  0.911392  0.848214  0.682353  3952  4772
pz_act14  0.927215  0.857143  0.752941  4958  5963
pz_act20  0.892405  0.848214  0.800000  3206  4385
pz_act25  0.901899  0.839286  0.823529  3718  4988

In [15]:
comp, recall = gen_tables(det_cats_files, true_cats_files, dict_cut={'M500' : [5, np.inf], 'b' : [20, np.inf]})
comp

<ipython-input-4-62a47b50d5ee>:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['b'] = sc.galactic.b.degree

,PSZ2,PSZ2_err,PSZ2_std,MCXC,MCXC_err,MCXC_std,ACT,ACT_err,ACT_std,all,fp
pz14,204,2.30,0.363463,48,0.80,0.224781,25,0.30,0.105131,7112,6266
pz20,204,2.20,0.312881,48,0.45,0.135239,25,0.10,0.068825,7329,6458
pz25,204,2.55,0.358909,48,0.60,0.183533,25,0.40,0.152177,7946,7082
pz40,203,2.50,0.387298,48,0.50,0.153897,25,0.40,0.133771,7678,6810
pz_act06,192,1.20,0.247088,48,0.50,0.198680,22,0.35,0.166623,2923,2263
pz_act10,194,1.55,0.223312,47,0.30,0.127733,23,0.15,0.081918,4772,3952
pz_act14,197,1.75,0.298020,47,0.65,0.220943,24,0.30,0.127733,5963,4958
pz_act20,188,1.70,0.262578,47,0.40,0.133771,23,0.25,0.099340,4385,3206
pz_act25,192,1.10,0.228266,47,0.25,0.123010,23,0.30,0.127733,4988,3718
all,206,0.00,NaN,57,0.00,NaN,27,0.00,NaN,0,0

In [16]:
recall

              PSZ2      MCXC       ACT    fp   all
pz14      0.990291  0.842105  0.925926  6266  7112
pz20      0.990291  0.842105  0.925926  6458  7329
pz25      0.990291  0.842105  0.925926  7082  7946
pz40      0.985437  0.842105  0.925926  6810  7678
pz_act06  0.932039  0.842105  0.814815  2263  2923
pz_act10  0.941748  0.824561  0.851852  3952  4772
pz_act14  0.956311  0.824561  0.888889  4958  5963
pz_act20  0.912621  0.824561  0.851852  3206  4385
pz_act25  0.932039  0.824561  0.851852  3718  4988

In [17]:
comp, recall = gen_tables(det_cats_files, true_cats_files, dict_cut={'b' : [20, np.inf]})
comp

<ipython-input-4-62a47b50d5ee>:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['b'] = sc.galactic.b.degree

,PSZ2,PSZ2_err,PSZ2_std,MCXC,MCXC_err,MCXC_std,ACT,ACT_err,ACT_std,all,fp
pz14,591,6.10,0.593385,332,9.50,0.748683,246,19.30,0.987021,7112,6266
pz20,608,7.10,0.496832,342,9.60,0.563822,251,18.75,0.790985,7329,6458
pz25,601,6.85,0.488149,345,9.00,0.676679,246,18.90,0.981138,7946,7082
pz40,597,6.70,0.607410,344,9.70,0.781699,256,19.80,1.340856,7678,6810
pz_act06,505,2.35,0.424729,261,4.50,0.483953,192,9.70,0.873890,2923,2263
pz_act10,538,3.75,0.415964,308,7.05,0.617614,302,13.50,0.738063,4772,3952
pz_act14,548,5.10,0.475173,314,8.80,0.713037,476,18.80,0.869362,5963,4958
pz_act20,512,4.20,0.456532,281,6.20,0.432861,690,15.35,1.119857,4385,3206
pz_act25,514,4.50,0.366348,277,5.80,0.526158,780,14.85,1.044472,4988,3718
all,644,0.00,NaN,917,0.00,NaN,1469,0.00,NaN,0,0

In [18]:
recall

              PSZ2      MCXC       ACT    fp   all
pz14      0.917702  0.362050  0.167461  6266  7112
pz20      0.944099  0.372955  0.170865  6458  7329
pz25      0.933230  0.376227  0.167461  7082  7946
pz40      0.927019  0.375136  0.174268  6810  7678
pz_act06  0.784161  0.284624  0.130701  2263  2923
pz_act10  0.835404  0.335878  0.205582  3952  4772
pz_act14  0.850932  0.342421  0.324030  4958  5963
pz_act20  0.795031  0.306434  0.469707  3206  4385
pz_act25  0.798137  0.302072  0.530973  3718  4988

In [19]:
comp, recall = gen_tables(det_cats_files, true_cats_files, dict_cut={'M500' : [3, np.inf],
                                                                    'z' : [-np.inf, 0.1], 
                                                                     'b' : [20, np.inf]})
comp

<ipython-input-4-62a47b50d5ee>:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['b'] = sc.galactic.b.degree

,PSZ2,PSZ2_err,PSZ2_std,MCXC,MCXC_err,MCXC_std,ACT,ACT_err,ACT_std,all,fp
pz14,22,0.30,0.127733,16,0.20,0.091766,2,0.00,0.000000,7112,6266
pz20,22,0.30,0.163836,17,0.15,0.081918,2,0.00,0.000000,7329,6458
pz25,24,0.40,0.133771,18,0.10,0.068825,3,0.00,0.000000,7946,7082
pz40,23,0.35,0.208693,16,0.30,0.146898,2,0.15,0.081918,7678,6810
pz_act06,24,0.20,0.091766,17,0.10,0.068825,3,0.05,0.050000,2923,2263
pz_act10,24,0.05,0.050000,17,0.15,0.081918,3,0.00,0.000000,4772,3952
pz_act14,24,0.35,0.131289,17,0.30,0.105131,3,0.05,0.050000,5963,4958
pz_act20,24,0.20,0.116980,19,0.05,0.050000,3,0.00,0.000000,4385,3206
pz_act25,24,0.60,0.152177,18,0.30,0.105131,3,0.10,0.068825,4988,3718
all,26,0.00,NaN,20,0.00,NaN,3,0.00,NaN,0,0

In [20]:
recall

              PSZ2  MCXC       ACT    fp   all
pz14      0.846154  0.80  0.666667  6266  7112
pz20      0.846154  0.85  0.666667  6458  7329
pz25      0.923077  0.90  1.000000  7082  7946
pz40      0.884615  0.80  0.666667  6810  7678
pz_act06  0.923077  0.85  1.000000  2263  2923
pz_act10  0.923077  0.85  1.000000  3952  4772
pz_act14  0.923077  0.85  1.000000  4958  5963
pz_act20  0.923077  0.95  1.000000  3206  4385
pz_act25  0.923077  0.90  1.000000  3718  4988

In [21]:
comp, recall = gen_tables(det_cats_files, true_cats_files, dict_cut={'M500' : [3, np.inf],
                                                                    'z' : [0.1, 0.3], 'b' : [20, np.inf]})
comp

<ipython-input-4-62a47b50d5ee>:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['b'] = sc.galactic.b.degree

,PSZ2,PSZ2_err,PSZ2_std,MCXC,MCXC_err,MCXC_std,ACT,ACT_err,ACT_std,all,fp
pz14,204,2.10,0.315394,107,1.05,0.211200,30,0.40,0.112390,7112,6266
pz20,206,2.60,0.425503,103,1.20,0.236198,29,0.35,0.131289,7329,6458
pz25,204,2.40,0.343358,102,1.50,0.256495,28,0.70,0.193309,7946,7082
pz40,204,2.10,0.289282,103,1.35,0.274101,28,0.75,0.270234,7678,6810
pz_act06,184,0.90,0.270477,95,0.65,0.254176,28,0.35,0.166623,2923,2263
pz_act10,192,1.35,0.310136,102,1.05,0.211200,29,0.35,0.131289,4772,3952
pz_act14,195,1.90,0.339504,102,1.50,0.256495,29,0.35,0.109424,5963,4958
pz_act20,187,1.40,0.244949,98,1.15,0.208693,30,0.20,0.091766,4385,3206
pz_act25,183,1.55,0.245753,95,0.95,0.223312,30,0.30,0.105131,4988,3718
all,206,0.00,NaN,131,0.00,NaN,33,0.00,NaN,0,0

In [22]:
recall

              PSZ2      MCXC       ACT    fp   all
pz14      0.990291  0.816794  0.909091  6266  7112
pz20      1.000000  0.786260  0.878788  6458  7329
pz25      0.990291  0.778626  0.848485  7082  7946
pz40      0.990291  0.786260  0.848485  6810  7678
pz_act06  0.893204  0.725191  0.848485  2263  2923
pz_act10  0.932039  0.778626  0.878788  3952  4772
pz_act14  0.946602  0.778626  0.878788  4958  5963
pz_act20  0.907767  0.748092  0.909091  3206  4385
pz_act25  0.888350  0.725191  0.909091  3718  4988

In [23]:
comp, recall = gen_tables(det_cats_files, true_cats_files, dict_cut={'M500' : [3, np.inf],
                                                                    'z' : [0.3, 0.6], 'b' : [20, np.inf]})
comp

<ipython-input-4-62a47b50d5ee>:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['b'] = sc.galactic.b.degree

,PSZ2,PSZ2_err,PSZ2_std,MCXC,MCXC_err,MCXC_std,ACT,ACT_err,ACT_std,all,fp
pz14,147,1.40,0.222427,30,0.45,0.114133,61,2.20,0.352435,7112,6266
pz20,148,1.60,0.293795,31,0.30,0.127733,63,1.50,0.328473,7329,6458
pz25,148,1.55,0.294467,31,0.25,0.099340,58,1.10,0.216430,7946,7082
pz40,148,1.85,0.364728,30,0.35,0.166623,60,1.85,0.318508,7678,6810
pz_act06,128,0.60,0.168585,30,0.15,0.081918,44,0.60,0.168585,2923,2263
pz_act10,130,1.10,0.216430,29,0.25,0.123010,59,0.95,0.223312,4772,3952
pz_act14,133,1.20,0.212751,30,0.30,0.127733,71,1.50,0.223607,5963,4958
pz_act20,126,1.05,0.276015,29,0.25,0.099340,78,1.50,0.235081,4385,3206
pz_act25,130,0.75,0.190221,29,0.10,0.100000,85,1.10,0.190567,4988,3718
all,148,0.00,NaN,43,0.00,NaN,118,0.00,NaN,0,0

In [24]:
recall

              PSZ2      MCXC       ACT    fp   all
pz14      0.993243  0.697674  0.516949  6266  7112
pz20      1.000000  0.720930  0.533898  6458  7329
pz25      1.000000  0.720930  0.491525  7082  7946
pz40      1.000000  0.697674  0.508475  6810  7678
pz_act06  0.864865  0.697674  0.372881  2263  2923
pz_act10  0.878378  0.674419  0.500000  3952  4772
pz_act14  0.898649  0.697674  0.601695  4958  5963
pz_act20  0.851351  0.674419  0.661017  3206  4385
pz_act25  0.878378  0.674419  0.720339  3718  4988

In [25]:
comp, recall = gen_tables(det_cats_files, true_cats_files, dict_cut={'M500' : [3, np.inf],
                                                                    'z' : [0.6, np.inf], 
                                                                     'b' : [20, np.inf]})
comp

<ipython-input-4-62a47b50d5ee>:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['b'] = sc.galactic.b.degree

,PSZ2,PSZ2_err,PSZ2_std,MCXC,MCXC_err,MCXC_std,ACT,ACT_err,ACT_std,all,fp
pz14,17,0.20,0.116980,5,0.00,0.000000,17,1.20,0.212751,7112,6266
pz20,19,0.00,0.000000,5,0.05,0.050000,15,1.15,0.220943,7329,6458
pz25,19,0.40,0.133771,5,0.15,0.109424,18,1.15,0.232549,7946,7082
pz40,18,0.20,0.116980,5,0.15,0.081918,20,1.45,0.198348,7678,6810
pz_act06,13,0.05,0.050000,1,0.05,0.050000,13,0.60,0.152177,2923,2263
pz_act10,15,0.10,0.068825,3,0.15,0.081918,21,0.90,0.260566,4772,3952
pz_act14,16,0.20,0.091766,4,0.20,0.116980,31,1.10,0.228266,5963,4958
pz_act20,14,0.15,0.081918,1,0.05,0.050000,55,1.00,0.217643,4385,3206
pz_act25,15,0.00,0.000000,2,0.05,0.050000,58,1.00,0.191943,4988,3718
all,19,0.00,NaN,5,0.00,NaN,86,0.00,NaN,0,0

In [26]:
recall

              PSZ2  MCXC       ACT    fp   all
pz14      0.894737   1.0  0.197674  6266  7112
pz20      1.000000   1.0  0.174419  6458  7329
pz25      1.000000   1.0  0.209302  7082  7946
pz40      0.947368   1.0  0.232558  6810  7678
pz_act06  0.684211   0.2  0.151163  2263  2923
pz_act10  0.789474   0.6  0.244186  3952  4772
pz_act14  0.842105   0.8  0.360465  4958  5963
pz_act20  0.736842   0.2  0.639535  3206  4385
pz_act25  0.789474   0.4  0.674419  3718  4988

In [9]:
comp, recall = gen_tables(det_cats_files, true_cats_files, {}, val_pix)
comp

<ipython-input-4-3f0b3aa26f4f>:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['b'] = sc.galactic.b.degree
<ipython-input-4-3f0b3aa26f4f>:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['b'] = sc.galactic.b.degree

,PSZ2,PSZ2_err,PSZ2_std,MCXC,MCXC_err,MCXC_std,RM,RM_err,RM_std,ACT,ACT_err,ACT_std,all,fp
pz14,148,0.80,0.200000,72,0.85,0.232549,141,15.50,0.904666,127,2.20,0.267542,1281,1055
pz20,151,1.05,0.211200,72,0.75,0.227977,149,15.10,0.858088,147,2.65,0.334625,1361,1116
pz25,150,0.85,0.232549,74,0.90,0.160591,159,16.35,0.915581,148,3.40,0.494177,1436,1187
pz40,147,0.70,0.179179,70,0.70,0.193309,149,16.60,0.847287,132,3.20,0.587591,1409,1180
pz_act06,123,0.15,0.081918,56,0.20,0.091766,73,6.40,0.449561,69,1.10,0.190567,524,375
pz_act10,144,0.85,0.166623,65,0.60,0.168585,108,8.60,0.678233,96,1.85,0.274101,814,624
pz_act14,143,0.85,0.181731,63,0.40,0.133771,117,12.80,0.613875,96,2.10,0.289282,947,759
pz_act20,133,0.20,0.091766,59,0.25,0.099340,90,8.45,0.752102,73,1.35,0.220943,716,557
pz_act25,132,0.45,0.153469,59,0.45,0.135239,98,9.45,0.626078,78,1.95,0.328273,787,624
all,160,0.00,NaN,166,0.00,NaN,3081,0.00,NaN,602,0.00,NaN,0,0

In [10]:
recall

             PSZ2      MCXC        RM       ACT    fp   all
pz14      0.92500  0.433735  0.045764  0.210963  1055  1281
pz20      0.94375  0.433735  0.048361  0.244186  1116  1361
pz25      0.93750  0.445783  0.051607  0.245847  1187  1436
pz40      0.91875  0.421687  0.048361  0.219269  1180  1409
pz_act06  0.76875  0.337349  0.023694  0.114618   375   524
pz_act10  0.90000  0.391566  0.035054  0.159468   624   814
pz_act14  0.89375  0.379518  0.037975  0.159468   759   947
pz_act20  0.83125  0.355422  0.029211  0.121262   557   716
pz_act25  0.82500  0.355422  0.031808  0.129568   624   787